name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

env:
  IMAGE_NAME: devops

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Lint Dockerfile
      #   uses: hadolint/hadolint-action@v3.1.0
      #   with:
      #     dockerfile: Dockerfile

      # Generate Docker image metadata
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,value=${{ github.sha }}
            type=ref,event=branch,pattern=main
            type=ref,event=branch,pattern={{branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
          labels: |
            org.opencontainers.image.source=$GITHUB_REPOSITORY

      # Set up QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          # build-args: |
          #   TERRAFORM_VERSION=${{ env.TERRAFORM_VERSION }}
          #   KUBE_VERSION=${{ env.KUBE_VERSION }}
          #   HELM_VERSION=${{ env.HELM_VERSION }}
          #   AWSCLI_VERSION=${{ env.AWSCLI_VERSION }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Test Docker Image
        run: |
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/devops-docker:latest aws --version
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/devops-docker:latest terraform --version
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/devops-docker:latest helm version
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/devops-docker:latest kubectl version --client
